### ISSUE TITLE
When a creature is killed instantly, the damage value will not be displayed

### ISSUE THREAD

**Issue by wsxiya** [jahirxtrap/healthindicatortxf#6]
When a creature is killed instantly, the damage value will not be displayed，Have you considered adding a healing particle effect?

**Comment by kuhananxianglai** [comment]
Is this what you mean? Yes, I think so too, healing particles are also an indispensable part of the Minecraft world (picture from another mod)
![屏幕截图 2024-08-23 211707](https://github.com/user-attachments/assets/0a73f714-05cb-43e9-9c85-4fcfe8604c86)

**Comment by jahirxtrap** [comment]
Healing particles added in 1.3.1
