### ISSUE TITLE
Help with blacklist

### ISSUE THREAD

**Issue by SomeGDPerson123** [jahirxtrap/healthindicatortxf#7]
I'm trying to blacklist multiple types of entities, but I don't know the formatting to properly do it. I tried spaces, and I tried commas. Didn't work.

**Comment by jahirxtrap** [comment]
The format is as follows:
```json
"blacklist": [
    "minecraft:pig",
    "minecraft:cow",
    "minecraft:chicken"
  ],
```

**Comment by SomeGDPerson123** [comment]
Is this for the options file or Mod Menu options menu? I'm using Mod Menu for the settings

**Comment by jahirxtrap** [comment]
Is for the config file, if you use the GUI simply type the entity id and click on the button with numbers (0, 1, 2...) to add new entries:
![image](https://github.com/user-attachments/assets/a3c9ab10-76cc-42ca-8e23-07706b2cacd9)

**Comment by SomeGDPerson123** [comment]
Ah, thank you!
